# permissions for end users to view finders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: finder-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-finder
    app.kubernetes.io/part-of: kube-finder
    app.kubernetes.io/managed-by: kustomize
  name: finder-viewer-role
rules:
- apiGroups:
  - kubefinder.tikalk.com
  resources:
  - finders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubefinder.tikalk.com
  resources:
  - finders/status
  verbs:
  - get
