---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubefinder.tikalk.com
  resources:
  - finders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubefinder.tikalk.com
  resources:
  - finders/finalizers
  verbs:
  - update
- apiGroups:
  - kubefinder.tikalk.com
  resources:
  - finders/status
  verbs:
  - get
  - patch
  - update
