apiVersion: v1
kind: Pod
metadata:
  name: faulty-pod-no-limit
spec:
  containers:
    - name: empty-debian-container
      image: ubuntu:latest
      resources:
          requests:
            cpu: "300000"
            memory: "50000Gi"

